cinemasite/cinemasite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from cinema_app.views import page_not_found
from cinemasite import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cinema_app.urls')),
    path('users/', include('users_app.urls', namespace='users')),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = page_not_found

admin.site.site_header = 'Панель администрирования'
admin.site.index_title = 'Сайт с крутыми фильмами'

cinemasite/users_app/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
]

cinemasite/templates/base.html
{% load static %}
{% load cinema_tags %}

<!DOCTYPE html>
<html>
<head>
	<title>{{title}}</title>
	<link type="text/css" href="{% static 'cinema_app/css/styles.css' %}" rel="stylesheet" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<link rel="shortcut icon" href="{% static 'cinema_app/images/logo.png' %}" type="image/x-icon"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<table class="table-page" border=0 cellpadding="0" cellspacing="0">
<tr><td valign=top>
{% block mainmenu %}
	<div class="header">
			<ul id="mainmenu" class="mainmenu">
			<li class="logo"><a href="{% url 'home' %}"><div class="logo"></div></a></li>
{% get_menu as menu %}
{% for m in menu %}
	<li><a href="{% url m.url_name %}">{{m.title}}</a></li>
{% endfor %}
{% if user.is_authenticated %}
	<li class="last"><a href="{% url 'home' %}">{{user.first_name}}</a> | <a href="{% url 'users:logout' %}">Выйти</a></li>
{% else %}
    <li class="last"><a href="{% url 'users:login' %}">Войти</a> | <a href="{% url 'users:register' %}">Регистрация</a></li>
{% endif %}
			</ul>
			<div class="clear"></div>
		</div>
{% endblock mainmenu %}


<table class="table-content" border=0 cellpadding="0" cellspacing="0">
<tr>
<!-- Боковая панель слева -->
	<td valign="top" class="left-chapters">
	<ul id="leftchapters">
		{% if cat_selected == 0 %}
			<li class="selected">Все категории</li>
		{% else %}
			<li><a href="{% url 'home' %}">Все категории</a></li>
		{% endif %}
		{% show_categories cat_selected %}
		<li><img src="{% static 'cinema_app/images/btwn.jpg' %}" width="225"></li>
		<li>{% show_genres %}</li>
	</ul>

</td>
<!-- Конец боковой панели -->

<td valign="top" class="content">
<!-- Блок контента -->
	<div class="content-text">
{% block content %}
{% endblock %}
	</div>

<!-- Отображение жанров -->
	{% block floor %}
	{% endblock %}
<!-- Конец блока контента -->

<!-- Блок отзывов -->

{% block feedback %}
	{% endblock %}


<!-- Пагинация -->
{% block pagination %}
{% endblock %}

</td></tr></table>
</td></tr>
<!-- Footer -->
<tr><td valign=top>
	<div id="footer">
		<p>&copy; 2024 by Ildar Kasimov</p>
	</div>
</td></tr></table>
<!-- Конец footer'а и страницы -->
</body>
</html>